[book]
authors = ["شركة Ankitects المملوكة المحدودة ومتطوعون"]
language = "ar"
multilingual = false
src = "src"
title = "الأسئلة المتكررة"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/abdnh/anki-faqs/"
additional-css = ["css/rtl.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
# quora dislikes bots
exclude = ['quora\.com']
